run:
  experiment_name: unigeomdist_novel_faust_000_007
  mode: eval
  env: local
  device: cuda
  seed: 0

paths:
  logs:
    local: /home/ben/LRZSyncShare/Thesis/Data/logs
    slurm: /home/stud/klb/storage/slurm/logs
  checkpoints:
    local: /home/ben/LRZSyncShare/Thesis/Data/checkpoints
    slurm: /home/stud/klb/storage/slurm/checkpoints
  samples: 
    local: /home/ben/LRZSyncShare/Thesis/Data/samples
  eval: 
    local: /home/ben/LRZSyncShare/Thesis/Data/eval

data:
  type: faust
  modalities:
    A: 3
    B: 3
  meshes:
    A:
      local: /home/ben/LRZSyncShare/Thesis/Data/data/MPI-FAUST/training/registrations/tr_reg_000.ply
      slurm: /home/stud/klb/storage/slurm/MPI-FAUST/training/registrations/tr_reg_000.ply
    B:
      local: /home/ben/LRZSyncShare/Thesis/Data/data/MPI-FAUST/training/registrations/tr_reg_007.ply
      slurm: /home/stud/klb/storage/slurm/MPI-FAUST/training/registrations/tr_reg_007.ply
  normalize: true
  normalize_samples: 10000000
  normalize_chunk: 1000000
  #shape_types: [sphere]

forward:
  type: ve_forward_process
  params: {}

model:
  type: diffusion_model
  params:
    conditioning:
      type: unidiff_hard_conditioning
      params: {}

    parametrization:
      type: x0_parametrization
      params: {}

    precond:
      type: edm_preconditioning
      params:
        sigma_data: 1.0

    point_embedder:
      type: geomdist_point_embedder
      params:
        token_dim: 256
        hidden_dim: 48

    sigma_embedder:
      type: geom_dist_fourier_embedder
      params:
        hidden_size: 256

    backbone:
      type: novel_backbone
      params:
        token_dim: 256
        sigma_dim: 256
        stem_depth: 2
        fusion_depth: 2
        head_depth: 1 # + 1 for final layer
        res_balance: 0.3

schedule:
  type: edm_sigma_schedule
  params:
    sigma_min: 0.002
    sigma_max: 80.0
    rho: 7.0
    P_mean: -1.2
    P_std: 1.2
    bias_strength_cond: 0.0
    bias_strength_other: 0.0

solver:
  type: heun_solver
  params:
    steps: 18
    s_churn: 0.0
    s_tmin: 0.0
    s_tmax: 1.0e9
    s_noise: 1.0

loss:
  type: geomdist_edm_loss
  params:
    sigma_data: 1.0

optim:
  type: adamw
  blr: 5e-7
  weight_decay: 0.05
  layerwise_decay: false
  layer_decay: 0.75
  lr_schedule:
    type: cosine_warmup
    params:
      warmup_epochs: 1
      max_epochs: 1000

train:
  #batch_size: 262144 
  batch_size: 87381
  steps_per_epoch: 512
  max_epochs: 1000
  log_every: 20
  checkpoint_every: 2
  conditional_sigma_prob: 0.0
  resample: epoch
  auto_resume: true
  #resume: latest

sample:
  checkpoint: checkpoint-epoch-0020.pth
  num_points: 10000
  steps: 64
  target: gaussian
  mode: conditional
  colorize_joint:
    enabled: true
    source_modality: A
  conditional:
    name: finger
    A: [0.421431,-0.492658,0.098006]
    # name: nose
    # A: [0.07243031,0.43507394,0.3256287]
  return_trajectory: false
  ascii: false
  guidance:
    enabled: true
    scale: 2.0

eval:
  checkpoint: checkpoint-epoch-0020.pth
  target: gaussian
  steps: 64
  geometry:
    enabled: true
    num_points: 100000
    ref_samples: 100000
    fscore_threshold: 0.01
    emd_max_points: 2048
    guidance:
      enabled: false
      scale: 3.0
  joint_correspondence:
    enabled: true
    source_modality: A
    num_points: 100000
  correspondence:
    enabled: true
    num_points: 10000
    num_pairs: 100
    specific_pair:
      enable: true
      name: nose
      observed_modality: A
      observed_point: [0.07243031, 0.43507394, 0.3256287]
      target_modality: B
      target_point: [0.12369011, 0.44195807, 0.30646071]
    guidance:
      enabled: false
      scale: 3.0

info:
  init_batch_size: 1
  profile_gpu_memory: true