run:
  experiment_name: geofusion_faust_000_007_034_051_096
  supervision: full
  mode: sample # train/sample/eval/info
  env: local # local/slurm
  device: cuda
  seed: 0

paths:
  logs:
    local: logs/
    slurm: logs/
  checkpoints:
    local: checkpoints/
    slurm: checkpoints/
  samples: 
    local: samples/
  eval: 
    local: eval/

data:
  type: faust # faust/dfaust/smal/smalr
  modalities:
    A: 3  # size of points
    B: 3
    C: 3
    D: 3
    E: 3
  meshes:
    A:
      local: /path/to/data/MPI-FAUST/training/registrations/tr_reg_000.ply
      slurm: /slurm/MPI-FAUST/training/registrations/tr_reg_000.ply
    B:
      local: /path/to/data/MPI-FAUST/training/registrations/tr_reg_007.ply
      slurm: /slurm/MPI-FAUST/training/registrations/tr_reg_007.ply
    C:
      local: /path/to/data/MPI-FAUST/training/registrations/tr_reg_034.ply
      slurm: /slurm/MPI-FAUST/training/registrations/tr_reg_034.ply
    D:
      local: /path/to/data/MPI-FAUST/training/registrations/tr_reg_051.ply
      slurm: /slurm/MPI-FAUST/training/registrations/tr_reg_051.ply
    E:
      local: /path/to/data/MPI-FAUST/training/registrations/tr_reg_096.ply
      slurm: /slurm/MPI-FAUST/training/registrations/tr_reg_096.ply
  normalize: true
  normalize_samples: 10000000
  normalize_chunk: 1000000
  #shape_types: [sphere]

forward:
  type: ve_forward_process
  params: {}

model:
  type: diffusion_model
  params:
    conditioning:
      type: unidiff_hard_conditioning
      params: {}

    parametrization:
      type: x0_parametrization
      params: {}

    precond:
      type: edm_preconditioning
      params:
        sigma_data: 1.0

    point_embedder:
      type: geomdist_point_embedder
      params:
        token_dim: 416
        hidden_dim: 48

    sigma_embedder:
      type: geom_dist_fourier_embedder
      params:
        hidden_size: 416

    backbone:
      type: geofusion_backbone # geomdist_backbone/dit_backbone/geofusion_backbone/dit_geomdist_backbone
      params:
        token_dim: 416
        sigma_dim: 416
        stem_depth: 2
        fusion_depth: 2
        head_depth: 1 # + 1 for final layer
        res_balance: 0.3

schedule:
  type: edm_sigma_schedule
  params:
    sigma_min: 0.002
    sigma_max: 80.0
    rho: 7.0
    P_mean: -1.2
    P_std: 1.2

solver:
  type: heun_solver
  params:
    steps: 18
    s_churn: 0.0
    s_tmin: 0.0
    s_tmax: 1.0e9
    s_noise: 1.0

loss:
  type: geomdist_edm_loss
  params:
    sigma_data: 1.0

optim:
  type: adamw
  blr: 5e-7
  weight_decay: 0.05
  layerwise_decay: false
  layer_decay: 0.75
  lr_schedule:
    type: cosine_warmup
    params:
      warmup_epochs: 1
      max_epochs: 1000

train:
  batch_size: 131072
  accum_iter: 1
  steps_per_epoch: 512
  max_epochs: 1000
  log_every: 20
  checkpoint_every: 10
  sigma_sampling:
    sigma_mode: clamp_joint  # default/clamp/joint/clamp_joint
    clamp_prob: 0.5
  resample: epoch
  auto_resume: false
  #resume: latest

sample:
  checkpoint: checkpoint-epoch-0999.pth
  num_points: 100000
  steps: 64
  target: gaussian
  mode: joint # joint/conditional
  colorize_joint: # add correspondence coloring
    enabled: true
    source_modality: A
  conditional: # set the point to condition on
    name: finger
    A: [0.421431,-0.492658,0.098006]
    # name: nose
    # A: [0.07243031,0.43507394,0.3256287]
  return_trajectory: false # diffusion trajectory
  trajectory_space: denoised
  ascii: false
  guidance:
    enabled: false
    scale: 3.0

eval:
  name_suffix: main
  checkpoint: checkpoint-epoch-0999.pth
  target: gaussian
  steps: 64
  geometry:
    enabled: true
    num_points: 100000
    ref_samples: 100000
    fscore_thresholds: [0.001, 0.003, 0.005]
    emd_max_points: 2048
    guidance:
      enabled: false
      scale: 3.0
  joint_correspondence:
    enabled: true
    source_modality: A
    num_points: 100000
  correspondence:
    enabled: true
    seed: 42
    num_points: 1000
    num_pairs: 1000
    specific_pair:
      enable: false
      name: nose
      observed_modality: A
      observed_point: [0.07243031, 0.43507394, 0.3256287]
      target_modality: B
      target_point: [0.12369011, 0.44195807, 0.30646071]
    guidance:
      enabled: false
      scale: 3.0

info:
  init_batch_size: 1
  profile_gpu_memory: true