run:
  experiment_name: geofusion_dfaust_50025_shake_arms_50009_punching
  supervision: full
  mode: train
  env: local
  device: cuda
  seed: 0

paths:
  logs:
    local: logs/
    slurm: logs/
  checkpoints:
    local: checkpoints/
    slurm: checkpoints/
  samples: 
    local: samples/
    slurm: samples/
  eval: 
    local: eval/

data:
  type: dfaust
  modalities:
    A: 4 # 3D + temporal component
    B: 4
  folder:
    local: /home/ben/LRZSyncShare/Thesis/Data/data/DFAUST
    slurm: /home/stud/klb/storage/slurm/DFAUST
  meshes:
    A:
      name: 50025_shake_arms
    B:
      name: 50009_punching
  times: true
  normalize: true
  normalize_samples: 10000000
  normalize_chunk: 1000000
  #shape_types: [sphere]

forward:
  type: ve_forward_process
  params: {}

model:
  type: diffusion_model
  params:
    conditioning:
      type: unidiff_hard_conditioning
      params: {}

    parametrization:
      type: x0_parametrization
      params: {}

    precond:
      type: edm_preconditioning
      params:
        sigma_data: 1.0

    point_embedder:
      type: geomdist_point_embedder
      params:
        token_dim: 416
        hidden_dim: 48

    sigma_embedder:
      type: geom_dist_fourier_embedder
      params:
        hidden_size: 416

    backbone:
      type: geofusion_backbone # geomdist_backbone/dit_backbone/geofusion_backbone/dit_geomdist_backbone
      params:
        token_dim: 416
        sigma_dim: 416
        stem_depth: 2
        fusion_depth: 2
        head_depth: 1 # + 1 for final layer
        res_balance: 0.3

schedule:
  type: edm_sigma_schedule
  params:
    sigma_min: 0.002
    sigma_max: 80.0
    rho: 7.0
    P_mean: -1.2
    P_std: 1.2

solver:
  type: heun_solver
  params:
    steps: 18
    s_churn: 0.0
    s_tmin: 0.0
    s_tmax: 1.0e9
    s_noise: 1.0

loss:
  type: geomdist_edm_loss
  params:
    sigma_data: 1.0

optim:
  type: adamw
  blr: 5e-7
  weight_decay: 0.05
  layerwise_decay: false
  layer_decay: 0.75
  lr_schedule:
    type: cosine_warmup
    params:
      warmup_epochs: 1
      max_epochs: 1000

train:
  # batch_size: 131072
  batch_size: 95000
  accum_iter: 1
  steps_per_epoch: 512
  max_epochs: 1000
  log_every: 20
  checkpoint_every: 10
  sigma_sampling:
    sigma_mode: clamp_joint  # default/clamp/joint/clamp_joint
    clamp_prob: 0.5
  resample: epoch
  auto_resume: true
  #resume: latest

sample:
  checkpoint: checkpoint-epoch-0999.pth
  num_points: 1000000
  steps: 64
  target: gaussian
  mode: joint
  colorize_joint:
    enabled: true
    source_modality: A
  conditional:
    name: finger
    A: [0.421431,-0.492658,0.098006]
    #A: [0.51120234,-0.31561434,0.20490514]
    # name: nose
    # A: [0.07243031,0.43507394,0.3256287]
  return_trajectory: false
  ascii: true
  guidance:
    enabled: false
    scale: 3.0

eval:
  checkpoint: checkpoint-epoch-0100.pth
  target: gaussian
  steps: 64
  geometry:
    enabled: true
    num_points: 100000
    ref_samples: 100000
    fscore_threshold: 0.01
    emd_max_points: 2048
    guidance:
      enabled: false
      scale: 3.0
  joint_correspondence:
    enabled: true
    source_modality: A
    num_points: 100000
  correspondence:
    enabled: true
    num_points: 10000
    num_pairs: 100
    specific_pair:
      enable: false
      name: nose
      observed_modality: A
      observed_point: [0.07243031, 0.43507394, 0.3256287]
      target_modality: B
      target_point: [0.12369011, 0.44195807, 0.30646071]
    guidance:
      enabled: false
      scale: 3.0

info:
  init_batch_size: 1
  profile_gpu_memory: true